### ISSUE TITLE
Method names should be nouns, not verbs

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/on-the-origin-of-objects#15]
We must change some of the names of the methods. Method names can be nouns or adjectives, but not verbs.
For example, `replace` should be changed to `replaced`, `join` to `joined`, and so on.

**Comment by EugeneDar** [comment]
Let me make it clear that this does not only apply to the names of string methods.

**Comment by EugeneDar** [comment]
@Graur @yegor256 what do you think?

**Comment by Graur** [comment]
@EugeneDar I'm ok with this

**Comment by EugeneDar** [comment]
@Graur please assign me this

**Comment by Graur** [comment]
@EugeneDar I have no permissions to do it here. Ask @yegor256, or just submit us a pull request

**Comment by EugeneDar** [comment]
@yegor256 assign me please

**Comment by yegor256** [comment]
@EugeneDar go ahead

**Comment by EugeneDar** [comment]
@yegor256 @Graur what do you think about `split` method. It seems to me that it doesn't need to be changed.

**Comment by EugeneDar** [comment]
@Graur I'll fix it
